eureka:
  instance:
    instance-id: zull-proxy
  client:
    serviceUrl:
      defaultZone: http://localhost:8260/eureka
server:
  port: 8888
spring:
  application:
    name: ZUULPROXY
zuul:
  routes:
    cosumer:
      path: /consumer-t/**
      serviceId: consumerservice
    user:
      path: /user-t/**
      #ignoredPatterns: /userservice
      serviceId: userservice
      sensitiveHeaders: Cookie,Set-Cookie
  #ignore-local-service: true
  ignored-services: "*"
token:
  header: X_Auth_Token
  appKey: admin
  secret: 123456
  expiration: 604800


